apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sakamchisto

resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: davidgjorgiev/sakamchisto-backend
    newTag: latest
  - name: davidgjorgiev/sakamchisto-frontend
    newTag: latest
